---
- hosts: all

  tasks:

    - name: Update repositories cache
      changed_when: False
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
      with_items:
        - openjdk-8-jdk

    - name: Close all open port 
      ufw: state=enabled policy=deny
  
    - name: Allow ssh traffic
      ufw: rule=allow port=22 proto=tcp

    - name: Allow traffic on port 8080
      ufw: rule=allow port=8080 proto=tcp

    - name: Add SSH deploy key used during workshop
      authorized_key: user=root key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDD55NN1dENsVTr5j7GDQUwyGX7oLej7VJvJPGW/gjhBc3wN/F/ctYSVTcUrSa3qRzjjZCYcGV3ubyAilyN2hka0OTOcnvGFYIwz+W/JrSIFr/60ivRhRcSqbwvYUjeJuCUsdK4BHGObYOxLjbdY1D43dloS87I/bfevKVrt1u2Gx091JbveKU9Xtk21ZHBhjW/1bR7r6DFCV6vjdmOQvX3urutrb53iK7+Cs4Rx1hZT+pwG5wCeY2SMjtZJwTx/qdZQDvpqOX9CWlrFhojjBMQNuFRj9oNEhH94tvcciZV4SeQHS/nnZzDdnOjSr2+Cy4lRNd1tAoj6I6xJEUXXAUj jam@deployment-key"
