---
- hosts: all

  tasks:

    - name: Update repositories cache
      changed_when: False
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
      with_items:
        - openjdk-8-jdk

    - name: Close all open port 
      ufw: state=enabled policy=deny
  
    - name: Allow ssh traffic
      ufw: rule=allow port=22 proto=tcp

    - name: Allow traffic on port 8080
      ufw: rule=allow port=8080 proto=tcp

    - name: Add SSH deploy key used during workshop
      authorized_key: user=root key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3khdUbttHnB4Ey6keD2gN+sIXIRvl/nUEqUrqqwN6ofhepGS9SZ2yt1k4EtlSt+tr2ZNKLd894WwqM7OR9VOvFBE52R0KywrCBkZMywUTM66t7Rj+QzORwAiACLmgaC3lkJt9XP3MG5ktHVBEUAeYcPs3coV2Pdvqejz9DHLyHEqVR9sCvvauop+JrfQskcnWjVCWw61KIKYZUlKTXmo2ahCLcSyxgODLx6QR4vCcGNuC5Jb8xbqHhtTtEjJN2FIY1XhlbhVPNisHxQa5Xk/h3g69wnQHFjqX8rKf52aDIEP+gDRf22UztkgXceM5NWqDVHXWTazspO8Z8CmQhhkF jam@deployment-key"
